# 例外処理  
## 例外  
* ある処理を実行した際の結果が、期待されるものと異なる状況を指す。  
* RubyおよびRuby on Railsでは、Exceptionというクラスを継承する形で様々な例外が定義されている。  
*  **NoMethodError** 、**SyntaxError** などは、全てExceptionクラスの子孫クラスで例外である。  
* 例外が発生すると、それ以降の処理は中止され、実行されなくなる。  
```
[<例>db/seeds.rb]
# ticket_countをint型で許容できる最大の値にする
User.find(500).update(ticket_count: 2147483647)
```
* もし。2147483647より大きな値を保存しようとすると、RangeErrorという例外が発生し、保存に失敗する。  
* ターミナルからrake distribute_ticket:executeを実行してみる。  
例外の発生するidが500までのユーザーについては、ticeket_countが10増加し、  
idが500番目以降のユーザーは、例外が発生し処理が中止され、ticket_countが増えない。  

## 例外処理  
* 例外が発生した場合に実行する処理のこと。  
* Ruby on Railsの開発を行う際に、よく利用するのがrescue。
* 繰り返し処理の内部にrescueを記述していた場合、例外が発生したとしても、次のループに移ることができる。
### rescueを用いた実装  
* rescueとは、発生した例外を捕捉し、例外が起こった際に呼び出される条件節。  
* 外が発生しそうな部分をbeginから始まるブロックで囲み、ブロックの内部にrescueを記述して使用する。  

```
(例)
begin
# 数字を0で割ろうとすると、ZeroDivisionError例外が発生する
  1 / 0
rescue
# 例外が発生した時にrescue以下の処理が呼ばれる
  puts '0で割ることはできません'
end
```
```
[例:lib/tasks/distribute_ticket.rake]
namespace :distribute_ticket do
  desc "全ユーザーのticket_countをrescueしながら10増加させる"
  task rescue: :environment do
    User.find_each do |user|
      begin
        user.increment!(:ticket_count, 10)
      //発生した例外をrescue節以下で'e'として扱うという意味
      rescue => e
        //発生した例外をログに記録する。 
        Rails.logger.debug e.message
      end
    end
  end
end
```
* レコードを操作するメソッド(save create update destroyなど)は、<br>実行に成功したらtrue、失敗したらfalseを返すため、例外を生じることがない。  
* 例外を意図的に発生させたい場合、**元々のメソッド名に「!」をつける**と、<br>実行に失敗した際にfalseを返すのではなく**例外を発生させる**ようになります。
(例)**save! create! destroy!**  
```
[ターミナル]
% rake distribute_ticket:rescue
```
* コマンドを実行後、Usersテーブルのticket_countの値が、<br>idが500以降のレコードについても、ticket_countが増加していれば成功です。

[![Image from Gyazo](https://i.gyazo.com/650a54a9cb3dfe2bf7db2b7c3f738485.png)](https://gyazo.com/650a54a9cb3dfe2bf7db2b7c3f738485)
## トランザクション  
* トランザクションとは、複数のレコードの更新を1つにまとめて行うことを指す。  
* トランザクションを用いることで、「全て実行されるか、それとも全て実行されないか」という1か0の状況を作ることができる。  
```
[例:、ECサイトでの購入処理を模した架空のコード]
# ECサイトの購入処理を模した架空のコード
ActiveRecord::Base.transaction do 
  current_user.pay!(@product.price)
  current_user.confirm_purchase!(@product)
end
```
* **pay!**メソッドで商品の料金を払い、**confirm_purchase!**メソッドで商品の注文を確定させている。  
* トランザクションを用いることによって下記問題を防ぐことができる。  
「料金の支払いに失敗したけど、商品は購入できた」  
「料金は支払ったけど、注文の確定に失敗し商品が届かなかった」  

```
[例:lib/tasks/distribute_ticket.rake]
# トランザクションのおかげで、例外が起こった際に何も変更されない
  desc "全ユーザーのticket_countをトランザクションで10増加させる"
  task transact: :environment do
    ActiveRecord::Base.transaction do
      User.find_each do |user|
        user.increment!(:ticket_count, 10)
      end
    end
  end
```
```
[ターミナル]
% rake distribute_ticket:rescue
```
* 実行後に、Usersテーブルを確認して、どのレコードも値が変化していなければ成功。
[![Image from Gyazo](https://i.gyazo.com/8a7388418c26f18b1c891218d4908c1d.png)](https://gyazo.com/8a7388418c26f18b1c891218d4908c1d)

> 参考  
[Ruby Exceptionクラス ドキュメント](https://docs.ruby-lang.org/ja/latest/class/Exception.html)  
[ActiveRecord Transactions ドキュメント(英語)](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)  







