# 例外処理  
## 例外的なエラー(Exception)  
プログラム実行時に下記エラーが発生  
[![Image from Gyazo](https://i.gyazo.com/2a962d984a93b6dfe421f579e7cde471.png)](https://gyazo.com/2a962d984a93b6dfe421f579e7cde471)
例外的なエラーー（Exception）が発生し、プログラムが異常終了したことを表している。  

## 例外処理とは？  
* コンパイル時には回避できないエラー(例外)を検知し、<br>例外が発生した際の処理をあらかじめ記述するためのもの。  
* 例外発生後の処理を記述することで、プログラムが異常終了することなく動作させることができる。  

## 例外処理の構文  
```
try {
    //例外が発生しうる処理;
//発生する可能性のある例外クラス名を書く。変数名は"e"or"ex"が用いられる。
} catch(例外クラス名 変数名) {
    //例外発生時の処理;
} finally {
    //(必要な場合のみ記述)例外発生有無にかかわらず必ず動作する処理;
}
```

## 例外クラスの一例  
| クラス名|概要|
|:--:|:--:|
|Exception| 何らかの例外|
|IOException |不正な入出力|
|IndexOutOfBoundsException |範囲外|
|ArithmeticException| 不正な算術計算|
|NullPointerException| Nullアクセス|  

* Exception以下はExceptionクラスを継承している。  
* Exceptionクラスを継承することで、独自の例外クラスを作成することもできる。

## Exceptionクラス  
* 下記メソッドが用意されており、クラスを継承した全てのクラスで利用することができる。  

| クラス名|概要|
|:--:|:--:|
|getMessage()| エラーメッセージを取得する。|
|printStackTrace() |※スタックトレースの内容を取得する。|

※スタックトレース：「メソッドがどの順番で呼び出され、どこで例外が発生したかが記録された情報」のことを指す。  

## 意図的に例外を発生させる（例外を投げる）方法  
```
         //必要な場合のみ記述
throw new 例外クラス名(“メッセージ“);
```
* 上記記述で意図的に例外を発生させる（例外を投げる）ことができる。  
* ()内にメッセージを記述すると、該当の例外クラスへメッセージを投げることが可能である。  

## 例外処理の例  
* 例外処理(1)
```
[Ex1.java]
public class Ex1 {
    public static void main(String[] args) {
        System.out.println("プログラムの実行");

        try {
            System.out.println("NullPointerExceptionを意図的に発生");
            throw new NullPointerException("ぬるぽ");
        //ExceptionクラスではなくNullPointerExceptionクラスがキャッチする。
        } catch(NullPointerException e) {
            System.out.println(e.getLocalizedMessage());
            System.out.println("エラー");
        } catch(Exception e) {
            System.out.println(e.getMessage());
            System.out.println("エラー発生したよ！");
        }
    }
}
>ターミナル
% javac.Ex1.jaba
% java Ex1
プログラムの実行
NullPointerExceptionを意図的に発生
ぬるぽ
エラー
```
* 例外処理(2)
```
[Ex1.java]
public class Ex1 {
    public static void main(String[] args) {
        System.out.println("プログラムの実行");

        try {
            System.out.println("IOExceptionを意図的に発生");
            throw new IOException();
            //直前で例外が発生しているため実行されない。
            System.out.println("ミスった");
        } catch(NullPointerException e) {
            System.out.println(e.getLocalizedMessage());
            System.out.println("エラー");
        //IOExceptionクラスでキャッチする処理が記述されていない為Exceptionクラスでキャッチされる。
        } catch(Exception e) {
            System.out.println(e.getMessage());
            System.out.println("エラー発生したよ！");
        }
    }
}
>ターミナル
% javac.Ex1.jaba
% java Ex1
プログラムの実行
IOExceptionを意図的に発生
null
エラー発生したよ！
```

## throws 例外クラス名  
* メソッド定義に加えることでメソッド内で例外が発生する可能性があることを示す。  
* メソッド内に```try~catch```を記述する必要は無くなるが、この記述が加えられたメソッドを呼び出す場合、<br>呼び出し元のメソッドでtry~catchが記述されてい
ないとコンパイルエラーとなる。

```
(例)
public void behavior() throws NullPointerException {
}
```


